// src/features/quiz/pages/ResultsPage.jsx
// Standalone result page (/results and /quiz/results).
//
// Reads the result saved by the quiz in this browser. It never depends on
// navigation state, so a refresh, a bookmark or a shared link still works.
// A stale persona can always be replaced: retaking the quiz overwrites the
// stored result immediately (deterministic scoring, no AI).

import React, { useMemo } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import QuizResultCard from '../components/QuizResultCard';
import { loadQuizResult, buildPersonaPreview, resolvePersonaParam } from '../lib/quizLogic.js';
import { PERSONA_KEYS } from '../lib/scoring.js';
import { getPersona } from '../lib/personas.js';
import DDSection from '../../../components/ui/DDSection';
import DDLabel from '../../../components/ui/DDLabel';
import DDCTA from '../../../components/ui/DDCTA';

function EmptyState() {
  return (
    <DDSection className="dd-section--hero">
      <div className="dd-container dd-container--narrow">
        <DDLabel tone="orange">Your result</DDLabel>
        <h1>No result on this device yet.</h1>
        <p>
          The quiz takes about two minutes and scores on this device. Once you finish, this page
          keeps your superpower, your blind spots and your build sequence.
        </p>
        <div className="action-row">
          <DDCTA label="Take the quiz" href="/quiz" variant="primary" />
          <DDCTA label="Back to home" href="/" variant="outline" />
        </div>
      </div>
    </DDSection>
  );
}

export default function ResultsPage() {
  const [searchParams] = useSearchParams();
  const stored = useMemo(() => loadQuizResult(), []);

  const requested = resolvePersonaParam(searchParams.get('type') || searchParams.get('persona'));

  const result = useMemo(() => {
    if (stored && (!requested || stored.superpower === requested)) return stored;
    if (requested) return buildPersonaPreview(requested);
    return null;
  }, [stored, requested]);

  if (!result) return <EmptyState />;

  const isPersonalized = result.source !== 'persona-template';
  const generated = result.generatedAt ? new Date(result.generatedAt) : null;
  const generatedLabel = generated && !Number.isNaN(generated.getTime())
    ? generated.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
    : '';

  return (
    <>
      <DDSection className="dd-section--hero dd-section--ink">
        <div className="dd-container">
          <DDLabel tone="blue">Step 03 / Result</DDLabel>
          <h1>
            {isPersonalized
              ? 'This is your result, scored from your own answers.'
              : 'A superpower overview you can explore.'}
          </h1>
          <p>
            {isPersonalized
              ? 'Nothing here was generated by a model. Seven answers, fixed weights, one build sequence.'
              : 'Take the quiz to replace this overview with your own strengths, blind spots and build order.'}
          </p>
          {generatedLabel ? <p className="hero-note hero-note--ink">Generated {generatedLabel}</p> : null}
        </div>
      </DDSection>

      <DDSection className="dd-section--story dd-section--white">
        <div className="dd-container">
          <QuizResultCard
            result={result}
            eyebrow={isPersonalized ? 'Your superpower' : `${getPersona(result.superpower).title} overview`}
            actions={
              <>
                <DDCTA label="Open my roadmap" href={`/roadmap/${result.superpower}`} variant="primary" />
                <DDCTA label="Retake the quiz" href="/quiz" variant="outline" />
              </>
            }
          />

          <div className="result-explore">
            <DDLabel tone="blue">Explore the other four</DDLabel>
            <div className="result-explore__grid">
              {PERSONA_KEYS.filter((key) => key !== result.superpower).map((key) => {
                const persona = getPersona(key);
                return (
                  <DDCTA
                    key={key}
                    label={persona.title}
                    href={`/roadmap/${key}`}
                    variant="outline"
                    className="result-explore__card"
                  />
                );
              })}
            </div>
          </div>
        </div>
      </DDSection>
    </>
  );
}