// src/features/quiz/pages/ResultsPage.jsx
// Standalone result page (/results and /quiz/results).
//
// Reads the result saved by the quiz in this browser. It never depends on
// navigation state, so a refresh, a bookmark or a shared link still works.
// A stale persona can always be replaced: retaking the quiz overwrites the
// stored result immediately (deterministic scoring, no AI).

import React, { useMemo } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import QuizResultCard from '../components/QuizResultCard.jsx';
import { loadQuizResult, buildPersonaPreview, resolvePersonaParam } from '../lib/quizLogic.js';
import { PERSONA_KEYS } from '../lib/scoring.js';
import { getPersona } from '../lib/personas.js';

function EmptyState() {
  return (
    <section className="page-hero">
      <div className="dd-container dd-container--narrow">
        <span className="label label--orange">Your result</span>
        <h1>No result on this device yet.</h1>
        <p>
          The quiz takes about two minutes and scores on this device. Once you finish, this page
          keeps your superpower, your blind spots and your build sequence.
        </p>
        <div className="action-row">
          <Link className="btn btn--primary" to="/quiz">Take the quiz →</Link>
          <Link className="btn btn--outline" to="/">Back to home</Link>
        </div>
      </div>
    </section>
  );
}

export default function ResultsPage() {
  const [searchParams] = useSearchParams();
  const stored = useMemo(() => loadQuizResult(), []);

  const requested = resolvePersonaParam(searchParams.get('type') || searchParams.get('persona'));

  const result = useMemo(() => {
    if (stored && (!requested || stored.superpower === requested)) return stored;
    if (requested) return buildPersonaPreview(requested);
    return null;
  }, [stored, requested]);

  if (!result) return <EmptyState />;

  const isPersonalized = result.source !== 'persona-template';
  const generated = result.generatedAt ? new Date(result.generatedAt) : null;
  const generatedLabel = generated && !Number.isNaN(generated.getTime())
    ? generated.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
    : '';

  return (
    <>
      <section className="page-hero page-hero--ink">
        <div className="dd-container">
          <span className="label label--blue">Step 03 / Result</span>
          <h1>
            {isPersonalized
              ? 'This is your result, scored from your own answers.'
              : 'A superpower overview you can explore.'}
          </h1>
          <p>
            {isPersonalized
              ? 'Nothing here was generated by a model. Seven answers, fixed weights, one build sequence.'
              : 'Take the quiz to replace this overview with your own strengths, blind spots and build order.'}
          </p>
          {generatedLabel ? <p className="hero-note hero-note--ink">Generated {generatedLabel}</p> : null}
        </div>
      </section>

      <section className="story-section story-section--white">
        <div className="dd-container">
          <QuizResultCard
            result={result}
            eyebrow={isPersonalized ? 'Your superpower' : `${getPersona(result.superpower).title} overview`}
            actions={
              <>
                <Link className="btn btn--primary" to={`/roadmap/${result.superpower}`}>
                  Open my roadmap →
                </Link>
                <Link className="btn btn--outline" to="/quiz">Retake the quiz</Link>
                <Link className="btn btn--outline" to="/dashboard">Open my dashboard →</Link>
              </>
            }
          />

          <div className="result-explore">
            <span className="label label--blue">Explore the other four</span>
            <div className="result-explore__grid">
              {PERSONA_KEYS.filter((key) => key !== result.superpower).map((key) => {
                const persona = getPersona(key);
                return (
                  <Link key={key} className="result-explore__card" to={`/roadmap/${key}`}>
                    <span className="label label--orange">{persona.title}</span>
                    <strong>{persona.superpowerName || persona.title}</strong>
                    <span className="result-explore__tagline">{persona.tagline}</span>
                  </Link>
                );
              })}
            </div>
          </div>
        </div>
      </section>
    </>
  );
}