import React, { useState, useMemo } from 'react';
import FadeInSection from '../../components/FadeInSection';
import DDCTA from '../../components/ui/DDCTA';
import DDLabel from '../../components/ui/DDLabel';
import { brutalCard, brutalHeading, brutalButtonPrimary, brutalButtonOutline, brutalBorder, theme } from '../../config/theme';
import { callAgent } from '../../lib/buzz-agents';

const fmtUSD = (n) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

export default function TenXROICalculator() {
  const [inputs, setInputs] = useState({ propertyName: 'Main Street Plumbing', leadTraffic: 45, avgJobValue: 1500, closeRate: 40, ppcCost: 65 });
  const [agentResult, setAgentResult] = useState(null);
  const [agentLoading, setAgentLoading] = useState(false);

  const result = useMemo(() => {
    const closedLeads = Math.floor(inputs.leadTraffic * (inputs.closeRate / 100));
    const grossRevenue = closedLeads * inputs.avgJobValue;
    const monthlyRent = grossRevenue / 40;
    const equityCap = grossRevenue * 0.1;
    const ppcSpend = inputs.leadTraffic * inputs.ppcCost;
    const savings = Math.max(ppcSpend - monthlyRent, 0);
    return { closedLeads, grossRevenue, monthlyRent, equityCap, ppcSpend, savings };
  }, [inputs]);

  const update = (key, value) => setInputs((previous) => ({ ...previous, [key]: value }));
  const comparisonMax = Math.max(result.ppcSpend, result.monthlyRent, 1);

  const askAgent = async () => {
    setAgentLoading(true);
    setAgentResult(null);
    try {
      const response = await callAgent('roadmap', { context: 'roi-calculator', inputs, result });
      setAgentResult(response.data || response);
    } catch (err) {
      setAgentResult('Agent unavailable right now.');
    } finally {
      setAgentLoading(false);
    }
  };

  return (
    <>
      <FadeInSection>
        <section className="page-hero">
          <DDLabel tone="blue">Digital Real Estate Yield Engine</DDLabel>
          <h1 style={{ ...brutalHeading, fontSize: 'clamp(1.6rem, 3.2vw, 2.4rem)', marginBottom: '1rem' }}>10X ROI Calculator</h1>
          <p className="hero__tagline" style={{ color: theme.colors.muted, fontFamily: theme.fonts.body }}>Model tenant revenue, a sustainable lease price, and the cost advantage your digital property creates.</p>
          <div className="action-row"><DDCTA label="Calculate My ROI →" href="#roi-calculator" variant="primary" /></div>
        </section>
      </FadeInSection>

      <FadeInSection delay={100}>
        <section className="section" id="roi-calculator">
          <div style={{ maxWidth: 1100, margin: '0 auto' }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.25rem' }}>
              <div style={{ ...brutalCard, padding: '1.25rem' }}>
                <DDLabel tone="orange" style={{ marginBottom: '0.5rem', display: 'inline-block' }}>Asset Metrics</DDLabel>
                <h2 style={{ ...brutalHeading, fontSize: '1.15rem', marginBottom: '1rem' }}>Enter the real traffic and economics behind this digital property.</h2>
                <div style={{ display: 'grid', gap: '1rem' }}>
                  {Object.entries(inputs).filter(([key]) => key !== 'propertyName').map(([key, value]) => (
                    <div key={key}>
                      <label className="form-label" style={{ fontFamily: theme.fonts.body }}>{key}</label>
                      <input className="form-input dd-input" type="number" value={value} onChange={(e) => update(key, Number(e.target.value))} style={{ fontFamily: theme.fonts.body }} />
                    </div>
                  ))}
                </div>
              </div>

              <div style={{ ...brutalCard, padding: '1.25rem', background: theme.colors.panel }}>
                <DDLabel tone="blue" style={{ marginBottom: '0.5rem', display: 'inline-block' }}>Revenue Summary</DDLabel>
                <h2 style={{ ...brutalHeading, fontSize: '1.15rem', marginBottom: '1rem' }}>Projected monthly value generated by {inputs.propertyName || 'this asset'}.</h2>
                <div style={{ marginBottom: '1rem' }}>
                  <div style={{ fontSize: '0.8rem', color: theme.colors.muted, textTransform: 'uppercase', fontFamily: theme.fonts.body }}>Total Yield Capability</div>
                  <div style={{ fontSize: '2rem', fontWeight: 900, fontFamily: theme.fonts.heading }}>{fmtUSD(result.grossRevenue)}</div>
                  <div style={{ fontSize: '0.9rem', color: theme.colors.muted, fontFamily: theme.fonts.body }}>Based on {result.closedLeads} closed calls at {fmtUSD(inputs.avgJobValue)} per job.</div>
                </div>
                <div style={{ display: 'grid', gap: '0.75rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(0,0,0,0.08)', paddingBottom: '0.5rem' }}>
                    <span style={{ fontFamily: theme.fonts.body }}>Equity Cap (10%)</span>
                    <strong style={{ fontFamily: theme.fonts.heading }}>{fmtUSD(result.equityCap)}<small style={{ marginLeft: '0.25rem', fontFamily: theme.fonts.body }}>/mo</small></strong>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid rgba(0,0,0,0.08)', paddingBottom: '0.5rem' }}>
                    <span style={{ fontFamily: theme.fonts.body }}>Lease Price (40X ROI)</span>
                    <strong style={{ fontFamily: theme.fonts.heading }}>{fmtUSD(result.monthlyRent)}<small style={{ marginLeft: '0.25rem', fontFamily: theme.fonts.body }}>/mo</small></strong>
                  </div>
                </div>
              </div>
            </div>

            <div style={{ marginTop: '1.25rem', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.25rem' }}>
              <div style={{ ...brutalCard, padding: '1.25rem' }}>
                <DDLabel tone="blue" style={{ marginBottom: '0.5rem', display: 'inline-block' }}>Market Comparison</DDLabel>
                <h2 style={{ ...brutalHeading, fontSize: '1.15rem', marginBottom: '1rem' }}>Compare the asset lease with paid search cost.</h2>
                <div style={{ display: 'grid', gap: '1rem' }}>
                  <div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                      <span style={{ fontFamily: theme.fonts.body }}>Digital Property Lease</span>
                      <strong style={{ fontFamily: theme.fonts.heading }}>{fmtUSD(result.monthlyRent)}</strong>
                    </div>
                    <div style={{ height: 10, background: '#e5e5e5', border: brutalBorder, marginTop: '0.25rem' }}>
                      <div style={{ height: '100%', width: `${Math.min(100, (result.monthlyRent / comparisonMax) * 100)}%`, background: theme.colors.orange, fontFamily: theme.fonts.heading }} />
                    </div>
                  </div>
                  <div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                      <span style={{ fontFamily: theme.fonts.body }}>Equivalent PPC Spend</span>
                      <strong style={{ fontFamily: theme.fonts.heading }}>{fmtUSD(result.ppcSpend)}</strong>
                    </div>
                    <div style={{ height: 10, background: '#e5e5e5', border: brutalBorder, marginTop: '0.25rem' }}>
                      <div style={{ height: '100%', width: `${Math.min(100, (result.ppcSpend / comparisonMax) * 100)}%`, background: theme.colors.aquaBlue, fontFamily: theme.fonts.heading }} />
                    </div>
                  </div>
                </div>
                <div style={{ marginTop: '1rem', ...brutalCard, padding: '1rem', borderLeft: `4px solid ${result.savings > 0 ? theme.colors.success : theme.colors.darkRed}`, fontFamily: theme.fonts.body }}>
                  <div style={{ fontSize: '0.8rem', color: theme.colors.muted, textTransform: 'uppercase', fontFamily: theme.fonts.body }}>Monthly Tenant Savings</div>
                  <div style={{ fontSize: '1.6rem', fontWeight: 900, fontFamily: theme.fonts.heading }}>{fmtUSD(result.savings)}</div>
                </div>
              </div>

              <div style={{ ...brutalCard, padding: '1.25rem' }}>
                <DDLabel tone="orange" style={{ marginBottom: '0.5rem', display: 'inline-block' }}>The Digital Landlord Pitch</DDLabel>
                <h2 style={{ ...brutalHeading, fontSize: '1.15rem', marginBottom: '1rem' }}>A concise explanation of the value this property delivers.</h2>
                <div style={{ display: 'grid', gap: '0.75rem', color: theme.colors.muted, lineHeight: 1.6, fontFamily: theme.fonts.body }}>
                  <p>“Hey [Name], I&rsquo;m auditing the traffic for my digital property, <strong>{inputs.propertyName}</strong>.”</p>
                  <p>“Last month, this asset delivered <strong>{result.closedLeads} exclusive calls</strong> directly to your phone.”</p>
                  <p>“Even if your team only converts <strong>{inputs.closeRate}%</strong>, that is <strong>{fmtUSD(result.grossRevenue)}</strong> in gross revenue generated by this property.”</p>
                  <p>“Replacing that traffic with Google Ads would cost <strong>{fmtUSD(result.ppcSpend)}</strong> plus agency fees. The exclusive territory lease is <strong>{fmtUSD(result.monthlyRent)}/month</strong>.”</p>
                </div>
                <button type="button" style={{ ...brutalButtonOutline, width: '100%', marginTop: '1rem', padding: '0.5rem 1rem', fontFamily: theme.fonts.body }} disabled={agentLoading} onClick={askAgent}>
                  {agentLoading ? 'Asking agent…' : 'Ask Hermes to improve this pitch'}
                </button>
                {agentResult && <div style={{ marginTop: '1rem', ...brutalCard, padding: '1rem', fontFamily: theme.fonts.body }}>{typeof agentResult === 'string' ? agentResult : JSON.stringify(agentResult, null, 2)}</div>}
              </div>
            </div>
          </div>
        </section>
      </FadeInSection>
    </>
  );
}
